### Health Check 
GET http://localhost:4000/api/health
### Health message
GET http://localhost:4000/api/health/message
### Health error 
GET http://localhost:4000/api/health/error
### Login
# @name login
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "active@test.com",
  "password": "Test@123456"
}

### Refresh
POST http://localhost:4000/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{login.response.body.refreshToken}}"
}

### Logout
POST http://localhost:4000/api/auth/logout
Authorization: Bearer {{login.response.body.accessToken}}

### Logout all
POST http://localhost:4000/api/auth/logout-all
Authorization: Bearer {{login.response.body.accessToken}}